{{- if .Values.executor.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autogpt-server-executor
  labels:
    {{- include "autogpt-server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autogpt-server-executor
  minReplicas: {{ .Values.executor.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.executor.autoscaling.maxReplicas }}
  metrics:
    - type: Object
      object:
        describedObject:
          apiVersion: v1
          kind: Service
          name: autogpt-server-executor
        metric:
          name: execution_manager_utilization_ratio_total
        target:
          type: Value
          value: {{ .Values.executor.autoscaling.targetUtilizationRatio }}

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
{{- end }}
