apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "autogpt-server.fullname" . }}-cert
spec:
  domains:
    - {{ .Values.domain }}
    {{- if and .Values.externalApiDomain (ne .Values.externalApiDomain "") }}
    - {{ .Values.externalApiDomain }}
    {{- end }}