apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "autogpt-server.fullname" . }}-migration
  labels:
    {{- include "autogpt-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "autogpt-server.fullname" . }}-migration
      labels:
        {{- include "autogpt-server.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
          - bash
          - -c
          - |
            cd /app/autogpt_platform/backend
            echo "Running database migrations..."
            poetry run prisma migrate deploy
            echo "Migrations completed!"
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
  backoffLimit: 3