# base values, environment specific variables should be specified/overwritten in environment values

replicaCount: 1

image:
  # All backend services use the same autogpt-server image with different entry points
  # Default to Docker Hub for open-source users
  # Override with your own registry:
  # e.g., us-central1-docker.pkg.dev/YOUR_PROJECT/autogpt/autogpt-server
  repository: autogpt/autogpt-server
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8005

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Probes configuration
livenessProbe:
  httpGet:
    path: /health_check
    port: 8005
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 30
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /health_check
    port: 8005
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 30
  failureThreshold: 3

# Sealed Secrets (disabled - using regular secrets)
sealedSecrets:
  enabled: false