apiVersion: batch/v1
kind: Job
metadata:
  name: autogpt-builder-build
  namespace: autogpt
spec:
  template:
    spec:
      containers:
      - name: docker-build
        image: docker:dind
        command:
        - sh
        - -c
        - |
          set -e
          echo "Starting Docker daemon..."
          dockerd-entrypoint.sh &
          sleep 10
          
          echo "Cloning AutoGPT repository..."
          apk add --no-cache git
          git clone https://github.com/Significant-Gravitas/AutoGPT.git /workspace
          cd /workspace
          
          echo "Building Docker image with .env.default..."
          docker build \
            -f autogpt_platform/frontend/Dockerfile \
            -t autogpt-builder-local:latest \
            .
          
          echo "Build complete!"
          docker images autogpt-builder-local:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        - name: docker-storage
          mountPath: /var/lib/docker
      restartPolicy: Never
      volumes:
      - name: docker-sock
        emptyDir: {}
      - name: docker-storage
        emptyDir: {}
  backoffLimit: 1