apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: autogpt
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: us-central1-docker.pkg.dev/agpt-dev/autogpt/autogpt-server:latest
        command: 
        - bash
        - -c
        - |
          cd /app/autogpt_platform/backend
          echo "Generating Prisma client..."
          poetry run prisma generate
          echo "Running database migrations..."
          poetry run prisma migrate deploy
          echo "Migrations completed!"
        env:
        - name: DATABASE_URL
          value: "postgresql://supabase:CHANGE-THIS-TO-A-SECURE-PASSWORD@supabase-postgresql.autogpt.svc.cluster.local:5432/supabase?schema=platform&connect_timeout=60"
        - name: DIRECT_URL
          value: "postgresql://supabase:CHANGE-THIS-TO-A-SECURE-PASSWORD@supabase-postgresql.autogpt.svc.cluster.local:5432/supabase?schema=platform&connect_timeout=60"
      restartPolicy: Never
  backoffLimit: 1