{{- if .Values.sharedConfig }}
{{- if .Values.sharedConfig.env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autogpt-database-manager.fullname" . }}-shared-config
  labels:
    {{- include "autogpt-database-manager.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.sharedConfig.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

{{- if .Values.sharedConfig.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "autogpt-database-manager.fullname" . }}-shared-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    {{- range $key, $value := .Values.sharedConfig.secrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ include "autogpt-database-manager.fullname" . }}-shared-secrets
      namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}