# Shared configuration for all AutoGPT services
# Include this in all Helm values files for consistent service discovery

sharedConfig:
  serviceHosts:
    RABBITMQ_HOST: "rabbitmq.autogpt.svc.cluster.local"
    RABBITMQ_PORT: "5672"
    RABBITMQ_DEFAULT_USER: "autogpt"
    
    REDIS_HOST: "redis-master.autogpt.svc.cluster.local"
    REDIS_PORT: "6379"
    
    AGENTSERVER_HOST: "autogpt-server.autogpt.svc.cluster.local"
    AGENTSERVER_PORT: "8006"
    
    SCHEDULER_HOST: "autogpt-scheduler.autogpt.svc.cluster.local"
    SCHEDULER_PORT: "8003"
    
    DATABASEMANAGER_HOST: "autogpt-database-manager.autogpt.svc.cluster.local"
    DATABASEMANAGER_PORT: "8005"
    
    EXECUTIONMANAGER_HOST: "autogpt-server-executor.autogpt.svc.cluster.local"
    EXECUTIONMANAGER_PORT: "8002"
    
    NOTIFICATIONMANAGER_HOST: "autogpt-notification.autogpt.svc.cluster.local"
    NOTIFICATIONMANAGER_PORT: "8003"
    
    WEBSOCKET_HOST: "autogpt-websocket-autogpt-websocket-server.autogpt.svc.cluster.local"  
    WEBSOCKET_PORT: "8001"
    
    # Additional ports for services
    AGENTSERVER_URL: "http://autogpt-server.autogpt.svc.cluster.local:8006"
    EXECUTIONMANAGER_URL: "http://autogpt-server-executor.autogpt.svc.cluster.local:8002"

  database:
    DB_CONNECTION_LIMIT: "10"
    DB_CONNECT_TIMEOUT: "60"
    DB_POOL_TIMEOUT: "300"
    
  performance:
    NUM_GRAPH_WORKERS: "10"