apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "supabase.name" . }}-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "supabase.name" . }}-auth
    app.kubernetes.io/instance: {{ .Release.Name }}