apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-kong
  labels:
    app.kubernetes.io/name: {{ include "supabase.name" . }}-kong
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kong
spec:
  type: {{ .Values.kong.service.type | default "ClusterIP" }}
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: proxy
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: proxy-ssl
  selector:
    app.kubernetes.io/name: {{ include "supabase.name" . }}-kong
    app.kubernetes.io/instance: {{ .Release.Name }}