apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.fullname" . }}-kong-config
  labels:
    app.kubernetes.io/name: {{ include "supabase.name" . }}-kong
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    ###
    ### Consumers / Users
    ###
    consumers:
      - username: anon
        keyauth_credentials:
          - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - username: service_role
        keyauth_credentials:
          - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q

    ###
    ### Access Control List
    ###
    acls:
      - consumer: anon
        group: anon
      - consumer: service_role
        group: admin

    services:
      # Health check service for root path - public access  
      - name: health-check
        url: http://{{ include "supabase.fullname" . }}-auth:9999/health
        routes:
          - name: health-check
            strip_path: false
            paths:
              - /
              - /health

      - name: auth-v1-open
        url: http://{{ include "supabase.fullname" . }}-auth:9999/verify
        routes:
          - name: auth-v1-open
            strip_path: true
            paths:
              - /auth/v1/verify
        plugins:
          - name: cors

      - name: auth-v1-open-callback
        url: http://{{ include "supabase.fullname" . }}-auth:9999/callback
        routes:
          - name: auth-v1-open-callback
            strip_path: true
            paths:
              - /auth/v1/callback
        plugins:
          - name: cors

      - name: auth-v1-open-authorize
        url: http://{{ include "supabase.fullname" . }}-auth:9999/authorize
        routes:
          - name: auth-v1-open-authorize
            strip_path: true
            paths:
              - /auth/v1/authorize
        plugins:
          - name: cors

      - name: auth-v1
        url: http://{{ include "supabase.fullname" . }}-auth:9999/
        routes:
          - name: auth-v1-all
            strip_path: true
            paths:
              - /auth/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      # Add REST API endpoint (returns empty response for Supabase client compatibility)
      - name: rest-v1-health
        url: http://{{ include "supabase.fullname" . }}-auth:9999/health
        routes:
          - name: rest-v1-all
            strip_path: false
            paths:
              - /rest/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      # Realtime, storage, and meta services are disabled

    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - X-Requested-With
            - Authorization
            - apikey
          exposed_headers:
            - X-Auth-Token
          max_age: 3600

      - name: request-transformer
        config:
          add:
            headers:
              - X-Client-Info:kong