apiVersion: v1
kind: Service
metadata:
  name: {{ include "autogpt-notification-server.fullname" . }}
  labels:
    {{- include "autogpt-notification-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: notifications
  selector:
    {{- include "autogpt-notification-server.selectorLabels" . | nindent 4 }}