# base values, environment specific variables should be specified/overwritten in environment values

replicaCount: 1

image:
  # Local build with .env.k8s-local for proper environment
  repository: us-central1-docker.pkg.dev/agpt-dev/autogpt/autogpt-builder
  pullPolicy: Always
  tag: "k8s-local"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 2Gi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  timeoutSeconds: 10
  periodSeconds: 15
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 90

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

domain: ""
wwwDomain: ""

# Sealed Secrets (disabled - using regular secrets)
sealedSecrets:
  enabled: false

env:
  # Server-side environment variables only
  # NEXT_PUBLIC_* vars come from .env in locally built Docker image
  AGPT_SERVER_URL: "http://autogpt-server:8006/api"
  SUPABASE_URL: "http://supabase-kong:8000"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q"