# base values, environment specific variables should be specified/overwritten in environment values

replicaCount: 1

image:
  # Default to Docker Hub for open-source users
  # Override with your own registry:
  # e.g., us-central1-docker.pkg.dev/YOUR_PROJECT/autogpt/autogpt-builder  
  repository: autogpt/autogpt-builder
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 2Gi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  timeoutSeconds: 10
  periodSeconds: 15
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 90

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

domain: ""
wwwDomain: ""

# Sealed Secrets (disabled - using regular secrets)
sealedSecrets:
  enabled: false

env:
  # Server-side environment variables only (Kubernetes service URLs)
  # NEXT_PUBLIC_* vars come from .env in locally built Docker image
  AGPT_SERVER_URL: "http://autogpt-server.autogpt.svc.cluster.local:8006/api"
  AGPT_WS_SERVER_URL: "ws://autogpt-websocket.autogpt.svc.cluster.local:8001/ws"
  SUPABASE_URL: "http://supabase-kong.autogpt.svc.cluster.local:8000"
  NEXT_PUBLIC_SUPABASE_URL: "http://supabase-kong.autogpt.svc.cluster.local:8000"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MVc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE"