# base values, environment specific variables should be specified/overwritten in environment values

replicaCount: 1

image:
  # Uses .env.default with TURNSTILE=disabled and BEHAVE_AS=LOCAL
  repository: us-central1-docker.pkg.dev/agpt-dev/autogpt/autogpt-builder
  pullPolicy: IfNotPresent
  tag: "local-default"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1280Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  timeoutSeconds: 10
  periodSeconds: 15
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

domain: ""
wwwDomain: ""

# Sealed Secrets (disabled - using regular secrets)
sealedSecrets:
  enabled: false

env:
  # Application Environment
  APP_ENV: "dev"
  NEXT_PUBLIC_APP_ENV: "dev"
  NEXT_PUBLIC_FRONTEND_BASE_URL: "http://localhost:3000"
  # Client-side URLs (NEXT_PUBLIC_*) - for browser requests via port-forward
  NEXT_PUBLIC_AGPT_SERVER_URL: "http://localhost:8006/api"
  NEXT_PUBLIC_SUPABASE_URL: "http://localhost:8000"
  NEXT_PUBLIC_AUTH_CALLBACK_URL: "http://localhost:3000/auth/callback"
  AUTH_CALLBACK_URL: "http://localhost:3000/auth/callback"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE"
  NEXT_PUBLIC_BEHAVE_AS: "CLOUD"
  NEXT_PUBLIC_TURNSTILE: "false"
  NEXT_PUBLIC_LAUNCHDARKLY_ENABLED: "true"
  # Server-side URLs (non-NEXT_PUBLIC_*) - for internal Kubernetes requests
  AGPT_SERVER_URL: "http://autogpt-server.autogpt.svc.cluster.local:80/api"
  SUPABASE_URL: "http://supabase-kong.autogpt.svc.cluster.local:8000"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q"
