{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ .Release.Name }}-rabbitmq-secrets
      namespace: {{ .Release.Namespace }}
{{- end }}