# base values, environment specific variables should be specified/overwritten in environment values

replicaCount: 1

image:
  # Default to Docker Hub for open-source users
  # Override with your own registry: 
  # e.g., us-central1-docker.pkg.dev/YOUR_PROJECT/autogpt/autogpt-server
  repository: autogpt/autogpt-server
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

serviceExecutor:
  type: ClusterIP
  port: 8002
  targetPort: 8002
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8002"
    prometheus.io/path: "/metrics"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1280Mi

executor:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetUtilizationRatio: "900m"
  terminationGracePeriodSeconds: 86400

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Sealed Secrets (disabled - using regular secrets)
sealedSecrets:
  enabled: false

domain: ""
externalApiDomain: ""

cors:
  allowOrigins:
    - "https://dev-builder.agpt.co"
  allowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowHeaders:
    - "Content-Type"
    - "Authorization"
  maxAge: 3600
  allowCredentials: true

env:
  PORT: "80"

