apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autogpt-builder.fullname" . }}-config
  labels:
    {{- include "autogpt-builder.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
